import MiniExtremalCombinatorics

#eval "══ Test.Smoke: mini-extremal-combinatorics import check ══"
#eval "Core/Basic.lean: SetFamily, binomial, isAntichain — OK"
#eval "Core/SetFamilies.lean: ijShift, LYM, shifting operations — OK"
#eval "Core/GraphExtremal.lean: SimpleGraph, Turán graph — OK"
#eval "Theorems/Sperner.lean: LYM, symmetric chains, compression proofs — OK"
#eval "Theorems/ErdosKoRado.lean: Intersecting families, stars — OK"
#eval "Theorems/Turan.lean: Turán's theorem, Mantel's theorem — OK"
#eval "Theorems/KruskalKatona.lean: Shadow bounds, colex order — OK"
#eval "Theorems/HallMarriage.lean: Hall's marriage theorem — OK"
#eval "Theorems/DilworthMirsky.lean: Dilworth & Mirsky theorems — OK"
#eval "Examples/ClassicExamples.lean: #eval examples — OK"
#eval "Applications/ToCodingTheory.lean: Coding theory — OK"
#eval "Applications/ToTheoreticalCS.lean: TCS — OK"
#eval "Advanced/SunflowerLemma.lean: Sunflower lemma — OK"
#eval "Advanced/RegularityLemma.lean: Regularity lemma — OK"
#eval "All 14 source modules imported successfully"
#eval "Package mini-extremal-combinatorics smoke test passed"
