-- AlgebraicCombinatorics.Research - research frontiers L9
import AlgebraicCombinatorics.Basic
namespace AlgebraicCombinatorics

/-! # Research Frontiers in Algebraic Combinatorics

  L9: Active research areas and open problems.
-/

section MacdonaldTheory

def macdonaldPositivity : String := 
  "Macdonald polynomials expand positively in Schur functions (Haiman 2001)."

def macdonaldHaimanModule : String :=
  "The Garsia-Haiman module DH_n has dimension (n+1)^{n-1} and 
   its bigraded Frobenius character is the nabla operator applied to e_n."

def deltaConjecture : String := 
  "Delta conjecture: combinatorial interpretation of Delta_{e_{n-k-1}} on e_n."

def rationalShuffleTheorem : String :=
  "The rational shuffle theorem (Mellit 2016): generalization of 
   the shuffle conjecture to rational slopes m/n."

end MacdonaldTheory

section KazhdanLusztigTheory

def combinatorialInvarianceConjecture : String := 
  "KL polynomials depend only on the Bruhat interval (open for general Weyl groups)."

def KLPolynomial (u v : Nat) (q : Nat) : Nat :=
  match u, v with
  | 0, 0 => 1 | 0, 1 => 1 | 0, 2 => 1+q
  | 1, 2 => 1 | _, _ => 0

def RPolynomial (u v : Nat) (q : Nat) : Nat :=
  match u, v with
  | 0, 0 => 1 | 0, 1 => q-1 | 0, 2 => q*(q-1)
  | _, _ => 0

def KazhdanLusztigBasis (_W : Type) : String :=
  "The KL basis {C_w} of the Hecke algebra satisfies positivity (Elias-Williamson 2014)."

end KazhdanLusztigTheory

section ClusterAlgebrasResearch

def fockGoncharovConjecture : String := 
  "Cluster structure on moduli spaces gives canonical basis (GHKK 2018)."

def clusterAlgebraDefinition : String :=
  "A cluster algebra A(x,B) is generated by cluster variables 
   obtained by iterated mutation from an initial seed (x,B)."

def laurentPhenomenon : String :=
  "Every cluster variable is a Laurent polynomial in the initial 
   cluster variables (Fomin-Zelevinsky 2002, proved)."

def positivityConjectureCluster : String :=
  "All cluster variables have positive integer coefficients 
   in any cluster (GHKK 2018, proved)."

end ClusterAlgebrasResearch

section ChromaticAndPositivity

def stanleyStembridgeConjecture : String := 
  "X_G is e-positive for (3+1)-free posets (open since 1993)."

def chromaticSymmetricFunction (G : String) : String :=
  s!"X_G: chromatic symmetric function of graph {G}"

def shareshianWachsConjecture : String :=
  "The chromatic quasisymmetric function refines X_G by ascent number."

end ChromaticAndPositivity

section PositiveGeometry

def positiveGrassmannian : String := 
  "Totally nonnegative Grassmannian is a cell complex (Arkani-Hamed-Trnka 2013)."

def amplituhedronCell : String := 
  "Cells of the amplituhedron correspond to on-shell diagrams in N=4 SYM."

def amplituhedronVolume : String := 
  "The volume of the amplituhedron computes scattering amplitudes."

end PositiveGeometry

section DiagonalHarmonics

def shuffleTheorem : String := 
  "Diagonal coinvariant ring character is nabla(e_n) (Carlsson-Mellit 2018)."

def diagonalHarmonics : String :=
  "The space DH_n of diagonal harmonics has dimension (n+1)^{n-1}."

def nablaOperator : String :=
  "The nabla operator is a linear operator on symmetric functions 
   defined by nabla(H_位) = t^{n(位)} q^{n(位')} H_位."

end DiagonalHarmonics

section CanonicalBases

def canonicalBases : String := 
  "Canonical bases (Lusztig, Kashiwara) provide combinatorial models 
   for representations of quantum groups."

def globalCrystalBase : String :=
  "The global crystal base of a quantum group representation 
   has remarkable positivity and integrality properties."

end CanonicalBases

section SpringerTheory

def spechtModules : String := 
  "Specht modules S^位 provide irreducible representations of S_n 
   over characteristic 0."

def springerFibers : String := 
  "Springer fibers and their cohomology connect representation theory 
   to geometry."

end SpringerTheory

section HilbertSchemes

def hilbertSchemes : String := 
  "Hilbert schemes of points on C^2 parametrize ideals and relate to 
   Macdonald polynomials."

def garsiaHaimanModule : String :=
  "The Garsia-Haiman module R_n is the coordinate ring of the 
   isospectral Hilbert scheme."

end HilbertSchemes

section TropicalGeometry

def tropicalGeometry : String := 
  "Tropical geometry provides combinatorial models for algebraic varieties."

def tropicalGrassmannian : String := 
  "The tropical Grassmannian parametrizes tropical linear spaces."

def tropicalFlagVariety : String :=
  "Tropical flag varieties generalize the tropical Grassmannian."

end TropicalGeometry

section MiscellaneousFrontiers

def clusterVarieties : String := 
  "Cluster varieties generalize toric varieties and host mirror symmetry."

def friezePatterns : String := 
  "Frieze patterns arise from mutations in cluster algebras of type A."

def LLT_polynomials : String := 
  "LLT polynomials generalize Hall-Littlewood polynomials and relate 
   to Macdonald theory."

def toricDegenerations : String := 
  "Toric degenerations of flag varieties relate to Grossberg-Karshon theory."

def positivityConjectures : String := 
  "Positivity phenomena in cluster algebras remain central open problems."

end MiscellaneousFrontiers

#eval "=== Research Topics Summary ==="
#eval macdonaldPositivity
#eval deltaConjecture
#eval shuffleTheorem
#eval fockGoncharovConjecture
#eval stanleyStembridgeConjecture
#eval positiveGrassmannian
#eval KLPolynomial 0 2 2
#eval KLPolynomial 1 2 2

end AlgebraicCombinatorics
